Update logistics.md
cpp-lln-lab/CPP_LabGuide pull request #62
Opened 2024-10-17 11:46 UTC by iqrashahzad14

Update logistics

2024-10-17 11:49 UTC, iqrashahzad14 commented
We need to also see that the access of MATLAB licence from The Sense is not public

2024-11-28 20:27 UTC, marcobarilari requested changes
Thanks for this, could check and link and make sure that follow the markdown rule? 

eg:
[link](url)

2024-11-28 20:27 UTC, marcobarilari commented on doc/logistics.md
> +If you are not directly paid by the university or a grant associated to it (eg. FNRS), so for instance if you are a WBI grant holder, you might need to set up your UCLouvain email adress yourself. To
```suggestion
If you are not directly paid by the university or a grant associated to it (eg. FNRS), so for instance if you are a WBI grant holder, you might need to set up your UCLouvain email adress yourself. To do so you first need to be registered as an invited researcher by the [GECO](https://uclouvain.be/fr/repertoires/entites/geco). You can contact Santina Bongiovanni santina.bongiovanni@uclouvain.be . They should give you your FGS number (“n° de matricule FGS” in French). You can then enter your FGS number as well as your birth date at this link https://sites.uclouvain.be/sgsi-apps/newaccount/prod/index.php?main=depart&stvl=en and that will give you your email address ! 

```

2024-11-28 20:27 UTC, marcobarilari commented on doc/logistics.md
> +From there, download the last version on your computer (or use matlab online). You will need to provide the credentials again during installation.
Maybe better to not disclose this

```suggestion
2. Matlab license from other Olivier's affiliation ask Olivier
```

2024-11-28 20:27 UTC, marcobarilari commented on doc/logistics.md
> +4. (NOT WORKING : License from UniTrento - Olivier’s permissions have changed.)
Better to not share publicly as well

```suggestion

```

2024-11-28 20:59 UTC, marcobarilari commented on doc/logistics.md
> +[code of rooms](https://uclouvain.sharepoint.com/:w:/r/sites/ipsy/_layouts/15/Doc.aspx?sourcedoc=%7BFC939836-CAE6-4444-B0F4-3CDF28EAC4B7%7D&file=Codes%20portes.docx&action=default&mobileredirect=true
We probably need to hide this, eg a link to a gsheet

2025-02-13 16:13 UTC, marcobarilari commented on doc/logistics.md
> +[code of rooms](https://uclouvain.sharepoint.com/:w:/r/sites/ipsy/_layouts/15/Doc.aspx?sourcedoc=%7BFC939836-CAE6-4444-B0F4-3CDF28EAC4B7%7D&file=Codes%20portes.docx&action=default&mobileredirect=true
https://docs.google.com/spreadsheets/d/1noz9ahlZZbodrDXmA0WsKUirx_jSje9D/edit?usp=sharing&ouid=108196860902997612702&rtpof=true&sd=true

2025-02-13 16:16 UTC, iqrashahzad14 commented on doc/logistics.md
> +[code of rooms](https://uclouvain.sharepoint.com/:w:/r/sites/ipsy/_layouts/15/Doc.aspx?sourcedoc=%7BFC939836-CAE6-4444-B0F4-3CDF28EAC4B7%7D&file=Codes%20portes.docx&action=default&mobileredirect=true
```suggestion
[code of rooms](https://docs.google.com/spreadsheets/d/1noz9ahlZZbodrDXmA0WsKUirx_jSje9D/edit?usp=sharing&ouid=108196860902997612702&rtpof=true&sd=true)

```

2025-02-13 16:18 UTC, marcobarilari approved these changes

2025-02-13 16:18 UTC, merged